service: pycon-bare-minimum

provider:
 name: aws
 region: ap-southeast-1
 runtime: python3.7

functions:
 hello:
   handler: handler.hello
   memorySize: 128
   timeout: 30
   events:
     - http:
         path: /api/v1/hello
         method: GET

package:
 exclude:
   - venv/**