
service: external-packages-without-layers


provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true  # makes a smaller package ~400KB vs. 800KB for request