
service: external-packages-without-layers


provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true
    